### PR TITLE
Make html template valid HTML

### PR DESCRIPTION
**Pull request by rpannek**
The template for the HTML page was invalid, which can be checked with https://validator.w3.org/. This patch adds a DOCTYPE and a the required <title>-tag. It also tries to make the HTML easier to read by rearanging it.

### CODE REVIEW

**Review by DunderRoffe — COMMENTED** [review]
When you are already in fixing. Do you mind splitting long lines?

Suggestion:
```html
<img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /> 
```

To
```html
<img alt="Creative Commons License"
     style="border-width:0"
     src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png"
/> 
```

**Comment by rpannek** [comment]
I guess I would rather remove the inline style attribute, stuff like that should be in CSS anyway. Normally people don't realle split single tags into multiple lines like that in the HTML world.

**Comment by DunderRoffe** [comment]
Sure, as long as I don't need to scroll horizontally in github reviews I am fine :)

**Comment by breakreturn** [comment]
There seems to be signed-off-by lines missing in the commits, unless I'm totally looking in the wrong place for the message.

**Comment by rpannek** [comment]
No, you're right, I didn't even think of that, need to find out how to do that.

**Comment by rpannek** [comment]
Now I squashed the commits and added a Signed-off-by: line.

**Comment by zeenix** [comment]
Do we really want "Signed-off-by" lines btw? In GDP I just continued the existing conventions but reading through this, I don't see much point of it at all:

http://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

If there are multiple authors, we can always add: co-author or co-authors at the end of the commit log.

**Comment by zeenix** [comment]
OTOH, a GPG signature is something that could be useful.

**Comment by jeremiah** [comment]
My view is that we need a Signed-off-by line when accepting patches/PR from outside contributors for the first time. Also, I think they're more appropriate around code and not documentation and presentation. That said, I should have followed the procedure and Signed-off.

**Review by jeremiah — COMMENTED** [review]
Thank you everyone for the constructive feedback. I hope to add more templates in the coming days.

**Comment by zeenix** [comment]
@jeremiah sure but I'd like to hear you opinion on what purpose they serve. Let's discuss face2face next week.

**Review by breakreturn — APPROVED** [review]

**Comment by breakreturn** [comment]
@zeenix What in that post makes you think we don't have any use for it? It essentially says that by connecting the Signed-off-by line with the DCO we have stated our requirements on the patch and asked the author to acknowledge it.

**Pull request merged**
