### PR TITLE
README.md: New link in Resources section

### PR DESCRIPTION
**Pull request by jeremiah**

### CODE REVIEW

**Review by DunderRoffe — APPROVED** [review]
Looks good. However, the commit is lacking a signature.

**Review by breakreturn — APPROVED** [review]
Looks good. It's our recommendation to sign off so I think that should be done (this is the template repo after all ;))

You can "git commit -s --amend" and then force push to your fork and this PR will be updated automatically.

**Review by GordanM — APPROVED** [review]

**Review by tobsan — APPROVED** [review]
Good, but I would also like to see the commit signed-off.

**Comment by jeremiah** [comment]
This is mostly a memory aide for myself but since I edited the README.md in the web interface and had to sign on the command line I did;

$ git checkout -b jeremiah-fsfe-reuse-patch origin/jeremiah-fsfe-reuse-patch
$ git commit -s --amend
$ git push -f origin

**Pull request merged**
