### PR TITLE
Squashing and new template 

### PR DESCRIPTION
**Pull request by jeremiah**
I've squashed some commits and added a new example template for Apache 2.0

### CODE REVIEW

**Comment by breakreturn** [comment]
Did you squash something that was already on the master branch?

**Review by DunderRoffe — CHANGES_REQUESTED** [review]
Looks good but it is not allowed to squash commits that are already pushed to master. If we were to merge this that would require us to force push to master which is a big no-no.

So unfortunately I have to ask you to make the changes to master as separate commits.

**Comment by jeremiah** [comment]
I would understand if this was a code directory, but this is just a bunch of templates where history is not that valuable. We've deviated from our policies for this repo in the past and I think for effeciency's sake it's worth doing again. I have to share the template with other parts of Luxoft and will be traveling for a few days so I won't get to this until later next week.

**Comment by breakreturn** [comment]
@jeremiah  The reason we don't allow squashes on master is because it changes the history that people have in their repos, but most importantly anything pointing to one of those revisions will break. Imagine a build somewhere that pulls down these templates and use them in the docs. That build would break if we do this.

So it's not about code, it's about how git works.

Why do you need to squash the master history anyway?

**Comment by tobsan** [comment]
I have to agree with @DunderRoffe and @breakreturn on this.

**Comment by DunderRoffe** [comment]
@jeremiah I have recreated your changes on top of master at https://github.com/Pelagicore/OpenSourceTemplates/tree/jeremiah-master-fix.

Should I close this PR and create a new PR for the fixed version?

Also fixed the formatting. All the flavor text were headings

**Comment by jeremiah** [comment]
Okay, I'll work on @DunderRoffe's new branch. Thanks for the formatting and I guess we close this PR and I'll create a new one.

@DunderRoffe Can you explain the concept of recreating the changes "on top" of master? Does this mean that we're just moving the stuff I squashed to a new branch and then going to merge it to HEAD which will keep the history in 'master'?

**Comment by jeremiah** [comment]
Closing this PR to use a new PR for jeremiah-master-fix branch.

**Pull request closed without merging**
